AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WorkshopUI:
    Type: 'AWS::IAM::ServiceLinkedRole'
    Properties:
      AWSServiceName: imagebuilder.amazonaws.com

  ParallelClusterUI:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: WorkshopUI
    Properties:
        TemplateURL: 'https://parallelcluster-ui-release-artifacts-us-east-1.s3.us-east-1.amazonaws.com/parallelcluster-ui.yaml'
        Parameters:
          AdminUserEmail: no-reply@amazon.com
          PublicEcrImageUri: public.ecr.aws/pcm/parallelcluster-ui:2023.02
          Version: '3.5.0'

Outputs:
   ParallelClusterUIUrl:
     Value:
       Fn::GetAtt:
           - ParallelClusterUI
           - Outputs.ParallelClusterUIUrl